language: crystal
crystal:
  - latest

env:
  global:
    - DATABASE_NAME=test
    - DATABASE_URL=mysql://root@localhost/$DATABASE_NAME

services:
  - mysql

before_install:
  - DATABASE_NAME=$DATABASE_NAME mysql -u root --password="" < test-data/setup.sql

script:
  - crystal spec
