language: bash

services:
  - docker

before_install:
  # build image using Dockerfile:
  - docker build -t testing .
  # GIT installed
  - git --version # => 2.21.0

script:
  # run specs in the container
  - docker run -v $PWD:/src -w /src testing crystal spec spec/game_of_life_spec.cr
  # GIT installed in Docker container
  - docker run -v $PWD:/src -w /src testing git --version # =>
