language: crystal
crystal:
  - latest

cache:
  directories:
    - lib
    - $HOME/.cache/shards

services:
  - mysql

before_install:
  - mysql -u root --password="" < test-data/setup.sql

script:
  - crystal spec
