language: crystal
crystal:
  - latest

env:
  - DATABASE_URL="mysql://root@localhost/test"

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS " $DATABASE_URL ";"
  - mysql -u root --password="" $DATABASE_URL < test-data/setup.sql

script:
  - crystal spec
