language: crystal
crystal:
  - latest

env:
  - DATABASE_URL="mysql://root@localhost/test"

services:
  - mysql

before_install:
  - mysql -u root --password="" < test-data/setup.sql

script:
  - crystal spec
