language: crystal

cache:
  directories:
    - lib

services:
  - mysql
  - docker

before_install:
  - mysql -u root --password="" < test-data/setup.sql

script:
  - docker run -v $PWD:/src -w /src crystallang/crystal:latest crystal spec
