language: bash

services:
  - docker

before_install:
  - sudo apt-get -y install git

addons:
  apt:
    update: true

script:
  - docker run -v $PWD:/src -w /src testing crystallang/crystal:0.30.0 spec spec/game_of_life_spec.cr
