language: crystal
crystal:
  - latest

cache:
  directories:
    - lib/
    - shard.lock

services:
  - mysql

before_install:
  - mysql -u root --password="" < travisci/test.sql

script:
  - crystal spec
