language: minimal

services:
  - docker

before_install:
  # build image using Dockerfile:
  - docker build -t testing .

script:
  # run specs in the container
  - docker run -v $PWD:/src -w /src testing crystal spec
