workflows:
  version: 2
  build:
    jobs:
      - crystal/test:
          name: test-on-nightly
          executor:
            name: crystal/docker
            tag: "0.30.0"
          spec-options: "./spec/game_of_life_spec.cr"

orbs:
  crystal: manastech/crystal@0.3
version: 2.1
