workflows:
  version: 2
  build:
    jobs:
      - crystal/test:
          pre-steps:
            - run: apt-get update && apt-get install -y libsqlite3-dev
          spec-options: "./spec/game_of_life_spec.cr"
orbs:
  crystal: manastech/crystal@0.3
version: 2.1
