version: 2.1

commands:
  run_build_and_test:
    steps:
      - checkout
      - run:
          name: list project files
          command: ls -lah
      - restore_cache:
          # Find the most recently generated cache used from any branch
          key: dependency-cache-
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache:
          key: dependency-cache-v1
          paths:
            - ./lib
            - ~/.cache/shards
      - run:
          name: version
          command: cat /etc/*-release
      - run:
          name: install dockerize
          command: apt-get update && apt-get install -y wget && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            apt-get install -y mysql-client
            mysql -h 127.0.0.1 -u root --password="" < test-data/setup.sql
      - run:
          name: test
          command: crystal spec
          environment:
            DATABASE_URL: mysql://root@localhost/test

executors:
  crystal-mysql:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: crystallang/crystal:<< parameters.tag >>
      - image: circleci/mysql:8.0.17
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

jobs:
  build-latest:
    executor: crystal-mysql
    steps:
      - run_build_and_test

  build-nightly:
    executor:
      name: crystal-mysql
      tag: "nightly"
    steps:
      - run_build_and_test

  build-0_30_0:
    executor:
      name: crystal-mysql
      tag: "0.30.0"
    steps:
      - run_build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-latest
      - build-nightly
      - build-0_30_0
