version: 2
jobs:
  build-latest:
    docker:
      - image: crystallang/crystal:latest
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_DATABASE: test
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: version
          command: cat /etc/*-release
      - run:
          name: install dockerize
          command: apt-get update && apt-get install -y curl && curl https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user --password="" test< test-data/test.sql
      - run:
          name: test
          command: crystal spec
  build-nightly:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - checkout
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: test
          command: crystal spec
  build-0_30_0:
    docker:
      - image: crystallang/crystal:0.30.0
    steps:
      - checkout
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: test
          command: crystal spec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-latest
      # - build-nightly
      # - build-0_30_0
