executors:
  crystal_mysql:
    docker:
      - image: 'crystallang/crystal:latest'
        environment:
          DATABASE_URL: 'mysql://root@localhost/db'
      - image: circleci/mysql:8.0.17
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: db
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

workflows:
  version: 2
  build:
    jobs:
      - crystal/test:
          executor: crystal_mysql
          pre-steps:
            - run:
                name: Waiting for service to start (check dockerize)
                command: sleep 1m
            - run:
                name: Install MySQL CLI; Import dummy data
                command: |
                  apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -u root --password="" < test-data/setup.sql

orbs:
  crystal: manastech/crystal@0.3
version: 2.1
