version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  crystal:
    executors:
      default:
        parameters:
          version:
            description: "Crystal version. Valid values: latest, nightly or M.m.p"
            type: string
            default: latest
        docker:
          - image: crystallang/crystal:<< parameters.version >>
    commands:
      cache_restore:
        steps:
          - restore_cache:
              keys:
                - shards-cache-{{ .Branch }}-{{ checksum "shard.yml" }}
                - shards-cache-{{ .Branch }}
                - shards-cache
          - restore_cache:
              keys:
                - shards-cache-{{ .Branch }}-{{ checksum "shard.lock" }}
                - shards-cache-{{ .Branch }}
                - shards-cache
      cache_save:
        steps:
          - save_cache:
              key: shards-cache-{{ .Branch }}-{{ checksum "shard.lock" }}
              paths:
                - ~/.cache/shards
          - save_cache:
              key: shards-cache-{{ .Branch }}-{{ checksum "shard.yml" }}
              paths:
                - ~/.cache/shards
      shards_install:
        steps:
          - run:
              name: Install dependencies.
              command: shards install
      test:
        parameters:
          spec_options: # files separated by space
            type: string
            default: ""
        steps:
          - run:
              name: run tests
              command: crystal spec << parameters.spec_options >>
    jobs:
      test:
        description: "Run tests with specified Crystal version"
        parameters:
          version:
            type: string
            default: latest
          spec_options:
            type: string
            default: ""
        executor:
          name: default
          version: << parameters.version >>
        steps:
          - checkout
          - cache_restore
          - shards_install
          - cache_save
          - test:
              spec_options: << parameters.spec_options >>

# DB executors
executors:
  crystal_mysql:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: crystallang/crystal:<< parameters.version >>
      - image: circleci/mysql:8.0.17
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          DATABASE_URL: mysql://root@localhost/test

# DB commands
commands:
  install_dockerize:
    parameters:
      version:
        type: string
        default: v0.6.1
    steps:
      - run:
          name: Install `curl` and `jq` for `docker/install-dockerize` command
          command: apt-get update && apt-get install -y curl jq
      - docker/install-dockerize
  wait_for_db:
    parameters:
      timeout:
        type: string
        default: 1m
      host:
        type: string
        default: tcp://localhost
      port:
        type: integer
        default: 3306
    steps:
      - install_dockerize
      - run:
          name: Wait for db using Dockerize
          command: dockerize -wait << parameters.host >>:<< parameters.port >> -timeout << parameters.timeout >>
  import_data:
    parameters:
      from:
        type: string
    steps:
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            apt-get install -y mysql-client
            mysql -h 127.0.0.1 -u root --password="" < << parameters.from >>

# DB jobs
jobs:
  test_with_db:
    parameters:
      executor:
        type: executor
      spec_options:
        type: string
        default: ""
    executor: << parameters.executor >>
    steps:
      - checkout
      - crystal/cache_restore
      - crystal/shards_install
      - crystal/cache_save
      - wait_for_db
      - import_data:
          from: "test-data/setup.sql"
      - crystal/test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_with_db:
          name: "Test with DB and latest"
          executor: crystal_mysql
      - test_with_db:
          name: "Test with DB and nightly"
          executor:
            name: crystal_mysql
            version: "nightly"
      - crystal/test:
          spec_options: "./spec/game_of_life_spec.cr"
