version: 2.1

orbs:
  db:
    orbs:
      docker: circleci/docker@0.5.20
    commands:
      install-dockerize:
        parameters:
          version:
            type: string
            default: v0.6.1
        steps:
          - run:
              name: Install `curl` and `jq` for `docker/install-dockerize` command
              command: apt-get update && apt-get install -y curl jq
          - docker/install-dockerize
      wait_for_db:
        parameters:
          timeout:
            type: string
            default: 1m
          host:
            type: string
            default: tcp://localhost
          port:
            type: integer
            default: 3306
        steps:
          - install-dockerize
          - run:
              name: Wait for db using Dockerize
              command: dockerize -wait << parameters.host >>:<< parameters.port >> -timeout << parameters.timeout >>
      import_data:
        parameters:
          from:
            type: string
        steps:
          - run:
              name: Install MySQL CLI; Import dummy data; run an example query
              command: |
                apt-get install -y mysql-client
                mysql -h 127.0.0.1 -u root --password="" < << parameters.from >>

  crystal:
    commands:
      cache_restore:
        steps:
          - restore_cache:
              keys:
                - shards-cache-{{ .Branch }}-{{ checksum "shard.lock" }}
                - shards-cache-{{ .Branch }}
                - shards-cache
      cache_save:
        steps:
          - save_cache:
              key: shards-cache-{{ .Branch }}-{{ checksum "shard.lock" }}
              paths:
                - ./lib
                - ~/.cache/shards
      shards_install:
        steps:
          - run:
              name: Install dependencies.
              command: shards install

commands:
  run_build_and_test:
    steps:
      - checkout
      - crystal/cache_restore
      - crystal/shards_install
      - crystal/cache_save
      - db/wait_for_db
      - db/import_data:
          from: "test-data/setup.sql"
      - run:
          name: test
          command: crystal spec
          environment:
            DATABASE_URL: mysql://root@localhost/test

executors:
  crystal-mysql:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: crystallang/crystal:<< parameters.tag >>
      - image: circleci/mysql:8.0.17
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

jobs:
  build-latest:
    executor: crystal-mysql
    steps:
      - run_build_and_test

  build-nightly:
    executor:
      name: crystal-mysql
      tag: "nightly"
    steps:
      - run_build_and_test

  build-0_30_0:
    executor:
      name: crystal-mysql
      tag: "0.30.0"
    steps:
      - run_build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-latest
      - build-nightly
      - build-0_30_0
