version: 2.1

commands:
  install_dockerize: # https://github.com/jwilder/dockerize
    steps:
      - run:
          name: Install dockerize.
          command: >-
            apt-get update &&
            apt-get install -y wget &&
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

jobs:
  build-latest:
    docker:
      - image: crystallang/crystal:latest
      - image: circleci/mysql:8.0.17
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: shards install
      - install_dockerize
      - run:
          name: Wait for db using Dockerize
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install MySQL CLI; Import dummy data
          command: |
            apt-get install -y mysql-client
            mysql -h 127.0.0.1 -u root --password="" < test-data/setup.sql
      - run:
          name: test
          command: crystal spec
          environment:
            DATABASE_URL: mysql://root@localhost/test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-latest
